### ISSUE TITLE
Vue block highlight

### ISSUE THREAD

**Issue by yyx990803** [khriztianmoreno/gist-blog-ssr#1]
FYI GitHub supports highlighting Vue single-file components (by tagging the code block with `vue`):

``` vue
<template>
  <div>{{ msg + '!!' }}</div>
</template>

<style lang="scss">
div {
  color: red;
}
</style>
```

**Comment by khriztianmoreno** [comment]
@yyx990803 thanks for the recommendation, since I am going to correct it, it is very helpful highlighting the code. :+1:  :computer: :+1:
